---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: test-metric-app 
  namespace: demo 
spec:
  updatePolicy:
    updateMode: "Off"
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-metric-app 
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 4000m
          memory: 1024Mi
        controlledResources: ["cpu", "memory"]
