apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  dnsNames:
    - keycloak.high10hunter.live
  secretName: keycloak-tls
  issuerRef:
    name: http-01-production
    kind: ClusterIssuer
