---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: docker-cluster-one 
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    classRef:
      name: quick-start
    controlPlane:
      replicas: 3 # Replicas changed from 1 to 3 
    variables:
    - name: imageRepository
      value: ""
    - name: etcdImageTag
      value: ""
    - name: coreDNSImageTag
      value: ""
    - name: podSecurityStandard
      value:
        audit: restricted
        enabled: true
        enforce: baseline
        warn: restricted
    version: v1.34.0
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1 

