apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-go
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - environment: dev
          - environment: stage
          - environment: prod
  template:
    metadata:
      name: "simple-go-{{.environment}}"
    spec:
      project: default
      sources:
        - repoURL: https://akuity.github.io/demo-helm-charts
          chart: simple-go
          targetRevision: 0.2.1
          helm:
            valueFiles:
              - $values/k8s/gitops/application-template/helm/values/common/values.yaml
              - $values/k8s/gitops/application-template/helm/values/env/{{.environment}}/values.yaml
        - repoURL: https://github.com/High10Hunter/k8s-lab-boilerplate.git
          targetRevision: main
          ref: values
      destination:
        # name: in-cluster
        name: remote
        namespace: "sg-{{.environment}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
