apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-metric-app
  namespace: demo
spec:
  selector:
    matchLabels:
      app: test-metric-app
  namespaceSelector:
    matchNames:
    - demo
  endpoints:
  - port: metrics
