---
apiVersion: v1
kind: Pod
metadata:
  name: app-1
  namespace: demo 
spec:
  containers:
    - name: test-metric-app-1
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: test-metric-app
---
apiVersion: v1
kind: Pod
metadata:
  name: app-2
  namespace: demo 
spec:
  containers:
    - name: test-metric-app-2
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: test-metric-app
