apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-019a6fccdd88e045d 
  directoryPerms: "700"
mountOptions:
  - iam
