---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
data:
  slack-token: eG94Yi02NzM5NjEwMzczNTc0LTg5NDc1MzM1MTkyNjQtZWVmTW95Z2x2M2NmeGlnSkR5QkFuQ0M3 
